[font]
size = 13

[font.normal]
family = "Consolas"

[window]
decorations = "full"

[window.padding]
x = 7
y = 0

[keyboard]

bindings = [
# Copy with Ctrl+Shift+C
{ key = "C", mods = "Control|Shift", action = "Copy" },
# Paste with Ctrl+Shift+P
  { key = "P", mods = "Control|Shift", action = "Paste" }
]

[[mouse.bindings]]
# Paste with Right Click
action = "Paste"
mouse = "Right"
